version: '3.8'

services:
  # redis service
  ecommerce-redis:
    image: redis/redis-stack-server:latest
    container_name: ecomerce_redis_stack
    privileged: true
    command:
      [
        'redis-server',
        '--bind',
        'ecommerce-redis',
        '--port',
        '6379',
        '--databases',
        '1600',
        '--requirepass',
        'ecommerce',
        '--loadmodule',
        '/opt/redis-stack/lib/redisearch.so',
        '--loadmodule',
        '/opt/redis-stack/lib/rejson.so',
      ]
    volumes:
      - redis_data:/data
    networks:
      - ecommerce
    ports:
      - 6379:6379
  # mysql database
  ecommerce-mysql:
    image: mariadb
    container_name: ecommerce_mysql
    restart: always
    cap_add: # suppresses  not useful error messages.
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: vfgetew2234*Wew
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecommerce
      MYSQL_PASSWORD: xyz344324wW
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ecommerce
  # nodejs server
  # server:
  #   container_name: server
  #   image: server:1.0.0
  #   ports:
  #     - 4000:4000
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   networks:
  #     - ecommerce
  #   env_file:
  #     - .env
  #   restart: unless-stopped

networks:
  ecommerce:
    driver: bridge
volumes:
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/redis
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/mysql
