version: '3.8'

services:
  # redis service
  ecommerce-redis:
    image: redis/redis-stack-server:latest
    container_name: ecomerce_redis_stack
    privileged: true
    command:
      [
        'redis-server',
        '--bind',
        'ecommerce-redis',
        '--port',
        '6379',
        '--databases',
        '1600',
        '--requirepass',
        'ecommerce',
        '--loadmodule',
        '/opt/redis-stack/lib/redisearch.so',
        '--loadmodule',
        '/opt/redis-stack/lib/rejson.so',
      ]
    volumes:
      - redis_data:/data
    networks:
      - ecommerce
    ports:
      - 6377:6379
  # mysql database
  ecommerce-mysql:
    image: mariadb
    container_name: ecommerce_mysql
    restart: always
    cap_add: # suppresses  not useful error messages.
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: vfgetew2234*Wew
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecommerce
      MYSQL_PASSWORD: xyz344324wW
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ecommerce
  # elastic search
  ecommerce-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: ecommerce_elasticsearch
    ports:
      - 9200:9200
    environment:
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
      - 'ES_JAVA_OPTS=-Xms1g -Xmx1g -Dhttp.port=9200'
    volumes:
      - elastic_search:/usr/share/elasticsearch/data
    networks:
      - ecommerce
  # nodejs server
  # server:
  #   container_name: server
  #   image: server:1.0.0
  #   ports:
  #     - 5000:5000
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   networks:
  #     - ecommerce
  #   depends_on:
  #     - ecommerce-redis
  #     - ecommerce-mysql
  #     - ecommerce-elasticsearch
  #   env_file:
  #     - .env
  #   restart: unless-stopped

networks:
  ecommerce:
    driver: bridge
volumes:
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/redis
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/mysql
  elastic_search:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/elastic-search
